version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./.env
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
    depends_on:
      - qdrant
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    env_file:
      - ./.env
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  qdrant_storage: